### ISSUE TITLE
All the dragon priest masks are bugged

### ISSUE THREAD

**Issue by AwesomeJames2120** [ForgottenGlory/Living-Skyrim-2#232]
![image](https://user-images.githubusercontent.com/44416823/85944388-b067de80-b979-11ea-85fb-3a86ab6071cf.png)
Upon equipping the wooden mask, the textures don't work. As you can see, this is very lame. Happens on both male and female regular humans, khajiit, argonians, and elves

![image](https://user-images.githubusercontent.com/44416823/85944483-66332d00-b97a-11ea-8586-9d8ffadb5d7b.png)
It does however work on orcs. lucky them

![image](https://user-images.githubusercontent.com/44416823/85944561-fbcebc80-b97a-11ea-8f2b-c086d0eeeb87.png)
The light version of konahriks mask

![image](https://user-images.githubusercontent.com/44416823/85944586-346e9600-b97b-11ea-8d07-29c60f997800.png)
This time the texture is borked on all races and sexes, how fair

**Comment by AwesomeJames2120** [comment]
Issue still persists on full release, with a new issue: The light version of konahriks masks enchantment description doesn't match the heavy version, as the use of capitals in "Health" is different. Also, would you mind making sure that the enchantment from Reliquary of myth applies to both versions of the mask? The description on both seems to be for the vanilla, not cool version instead of the cool modded one.

**Comment by AwesomeJames2120** [comment]
Oh, and another thing, Morokei has an armoured light version of his robe, but not for his hand and feet bits in the Konahriks mod. Whilst its not necessary it would be extremely cool if you could fix this issue. Furthermore, could you please add a light armoured version of the mask to go with it?

**Comment by AwesomeJames2120** [comment]
After some more testing, none of the mask effects from reliquary of myth work at all, and are instead all vanilla. Needless to say, this is extreemly not good considering the many improvements over the originals reliquary makes
![image](https://user-images.githubusercontent.com/44416823/86498876-2f6e7400-bdcb-11ea-84c2-db746adbb994.png)
In addition, the texture of the actual mask on females is instead the hood texture of the mask
![image](https://user-images.githubusercontent.com/44416823/86498916-72c8e280-bdcb-11ea-94fd-d5c0e5333622.png)

**Comment by ForgottenGlory** [comment]
All except Zahkriisos are fixed, still working on that one. Unsure what's up with it.

**Comment by AwesomeJames2120** [comment]
Other than the wooden mask, the issues still persist in the latest version.
In short:
All masks are using their vanilla enchants, instead of the improved ones from reliquary of myth
Light version of konahriks mask still uses vanilla textures
Morokeis armoured robes exist, but the boots and gloves don't have an armoured variation
