### ISSUE TITLE
Nordic Leather Nasal Helmet is free-floating

### ISSUE THREAD

**Issue by LunarDelta** [ForgottenGlory/Living-Skyrim-2#372]
**LS Version**
2.2.1

**Describe the bug**
The Nordic Leather Nasal Helmet floats in the air around both you and NPCs as you move around. It eventually catches up with you but never stays put. Inventory view is also glitched.

**To Reproduce**
Wear the helmet, or find an NPC wearing it, or look at it in the inventory.

**Expected behavior**
I expected the helmet to be on my head like normal.

**Screenshots**
![SkyrimSE 2020-08-08 08-27-18](https://user-images.githubusercontent.com/29786040/89712283-e5deef00-d95d-11ea-9097-f3b35c7d8c02.png)
![SkyrimSE 2020-08-08 08-27-57](https://user-images.githubusercontent.com/29786040/89712285-e7a8b280-d95d-11ea-986e-38d489283a75.png)
![SkyrimSE 2020-08-08 09-51-21](https://user-images.githubusercontent.com/29786040/89712288-e9727600-d95d-11ea-8c30-30df6d6a4fde.png)

**Comment by TwistedModding** [comment]
you need to select it in the console for it to be fixed

**Comment by LunarDelta** [comment]
I tried that just now, but the item is unselectable. It either vanishes the instant I drop it, or floats in place and becomes completely intangible and unclickable. Here's a screenshot of the information I could look up using console commands:
![Capture](https://user-images.githubusercontent.com/29786040/89716892-e340c180-d97e-11ea-9de8-f9d62b754af8.PNG)

**Comment by LTYNS** [comment]
I have the exact same problem, including it being unselectable in console.

**Comment by ForgottenGlory** [comment]
I know the helmet in question, I'll fix it for the next update.

**Comment by ForgottenGlory** [comment]
Fixed 2.3.0

**Comment by seanpbelcher** [comment]
Still an issue for me, but with another piece from the Nordic set.
![enb2020_9_8_05_40_19](https://user-images.githubusercontent.com/67465410/92469473-7a758080-f19a-11ea-99d0-f682ae62f46e.jpg)
![enb2020_9_8_05_38_47](https://user-images.githubusercontent.com/67465410/92469524-90834100-f19a-11ea-97e9-b011c9e270ef.jpg)
